Add getopt_long_only().

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -1,4 +1,4 @@
-PROGS = getopt_test getopt_long_test ya_getopt_test ya_getopt_long_test
+PROGS = getopt_test getopt_long_test getopt_long_only_test ya_getopt_test ya_getopt_long_test ya_getopt_long_only_test
 CFLAGS = -Wall
 
 all: $(PROGS)
@@ -38,6 +38,21 @@ check: $(PROGS)
 	                "--baz=val" \
 	                "--qux=val" \
 	                "--quux=val" \
+	                "-foo" \
+	                "-bar" \
+	                "-baz" \
+	                "-qux" \
+	                "-quux" \
+	                "-foo val" \
+	                "-bar val" \
+	                "-baz val" \
+	                "-qux val" \
+	                "-quux val" \
+	                "-foo=val" \
+	                "-bar=val" \
+	                "-baz=val" \
+	                "-qux=val" \
+	                "-quux=val" \
 	                "-a foo -b bar" \
 	                "-a -- -b bar" \
 	                "-a --- -b bar" \
@@ -56,8 +71,10 @@ check: $(PROGS)
 	      echo -n .; \
 	      env OPTSTRING=$$optstring ./getopt_test $$args 2> getopt_test.out; \
 	      env OPTSTRING=$$optstring ./getopt_long_test $$args 2> getopt_long_test.out; \
+	      env OPTSTRING=$$optstring ./getopt_long_only_test $$args 2> getopt_long_only_test.out; \
 	      env OPTSTRING=$$optstring ./ya_getopt_test $$args 2> ya_getopt_test.out; \
 	      env OPTSTRING=$$optstring ./ya_getopt_long_test $$args 2> ya_getopt_long_test.out; \
+	      env OPTSTRING=$$optstring ./ya_getopt_long_only_test $$args 2> ya_getopt_long_only_test.out; \
 	      if ! cmp getopt_test.out ya_getopt_test.out >/dev/null; then \
 	        echo; \
 	        echo OPTSTRING=\'$$optstring\' ARGS=\'$$args\' ... FAILED; \
@@ -68,6 +85,12 @@ check: $(PROGS)
 	        echo; \
 	        echo -n OPTSTRING=\'$$optstring\' ARGS=\'$$args\' ... FAILED; \
 	        diff -u getopt_long_test.out ya_getopt_long_test.out | head -20; \
+	        exit 1; \
+	      fi; \
+	      if ! cmp getopt_long_only_test.out ya_getopt_long_only_test.out >/dev/null; then \
+	        echo; \
+	        echo -n OPTSTRING=\'$$optstring\' ARGS=\'$$args\' ... FAILED; \
+	        diff -u getopt_long_only_test.out ya_getopt_long_only_test.out | head -20; \
 	        exit 1; \
 	      fi; \
 	    done; \
@@ -82,11 +105,17 @@ getopt_test: getopt_test.c
 getopt_long_test: getopt_long_test.c
 	$(CC) $(CFLAGS) -o getopt_long_test getopt_long_test.c
 
+getopt_long_only_test: getopt_long_only_test.c
+	$(CC) $(CFLAGS) -o getopt_long_only_test getopt_long_only_test.c
+
 ya_getopt_test: getopt_test.c ../ya_getopt.c ../ya_getopt.h
 	$(CC) $(CFLAGS) -o ya_getopt_test -DUSE_YA_GETOPT -I.. getopt_test.c  ../ya_getopt.c
 
 ya_getopt_long_test: getopt_long_test.c ../ya_getopt.c ../ya_getopt.h
 	$(CC) $(CFLAGS) -o ya_getopt_long_test -DUSE_YA_GETOPT -I.. getopt_long_test.c  ../ya_getopt.c
 
+ya_getopt_long_only_test: getopt_long_only_test.c ../ya_getopt.c ../ya_getopt.h
+	$(CC) $(CFLAGS) -o ya_getopt_long_only_test -DUSE_YA_GETOPT -I.. getopt_long_only_test.c  ../ya_getopt.c
+
 clean:
-	$(RM) $(PROGS) getopt_test.out getopt_long_test.out ya_getopt_test.out ya_getopt_long_test.out
+	$(RM) $(PROGS) getopt_test.out getopt_long_test.out getopt_long_only_test.out ya_getopt_test.out ya_getopt_long_test.out ya_getopt_long_only_test.out
