Add getopt_long().

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -1,14 +1,15 @@
+PROGS = getopt_test getopt_long_test ya_getopt_test ya_getopt_long_test
 CFLAGS = -Wall
 
-all: getopt_test ya_getopt_test
+all: $(PROGS)
 
-check: getopt_test ya_getopt_test
-	@ulimit -t 1; \
-	for c in 1 2; do \
+check: $(PROGS)
+	@for c in 1 2; do \
 	  if test $$c -eq 1; then \
 	    echo ===== with POSIXLY_CORRECT =====; \
 	    export POSIXLY_CORRECT=; \
 	  else \
+	    echo; \
 	    echo ===== without POSIXLY_CORRECT =====; \
 	    unset POSIXLY_CORRECT; \
 	  fi; \
@@ -22,6 +23,21 @@ check: getopt_test ya_getopt_test
 	                "-b" \
 	                "-acb" \
 	                "-abc" \
+	                "--foo" \
+	                "--bar" \
+	                "--baz" \
+	                "--qux" \
+	                "--quux" \
+	                "--foo val" \
+	                "--bar val" \
+	                "--baz val" \
+	                "--qux val" \
+	                "--quux val" \
+	                "--foo=val" \
+	                "--bar=val" \
+	                "--baz=val" \
+	                "--qux=val" \
+	                "--quux=val" \
 	                "-a foo -b bar" \
 	                "-a -- -b bar" \
 	                "-a --- -b bar" \
@@ -37,23 +53,40 @@ check: getopt_test ya_getopt_test
 	                "-barg foo bar baz -barg qux" \
 	                "-barg foo bar baz -barg qux quux" \
 	                "-a foo -b bar -a baz -c qux"; do \
+	      echo -n .; \
 	      env OPTSTRING=$$optstring ./getopt_test $$args 2> getopt_test.out; \
+	      env OPTSTRING=$$optstring ./getopt_long_test $$args 2> getopt_long_test.out; \
 	      env OPTSTRING=$$optstring ./ya_getopt_test $$args 2> ya_getopt_test.out; \
+	      env OPTSTRING=$$optstring ./ya_getopt_long_test $$args 2> ya_getopt_long_test.out; \
 	      if ! cmp getopt_test.out ya_getopt_test.out >/dev/null; then \
+	        echo; \
 	        echo OPTSTRING=\'$$optstring\' ARGS=\'$$args\' ... FAILED; \
 	        diff -u getopt_test.out ya_getopt_test.out | head -20; \
+	        exit 1; \
+	      fi; \
+	      if ! cmp getopt_long_test.out ya_getopt_long_test.out >/dev/null; then \
+	        echo; \
+	        echo -n OPTSTRING=\'$$optstring\' ARGS=\'$$args\' ... FAILED; \
+	        diff -u getopt_long_test.out ya_getopt_long_test.out | head -20; \
 	        exit 1; \
 	      fi; \
 	    done; \
 	  done; \
 	done
+	@echo
 	@echo PASS ALL
 
 getopt_test: getopt_test.c
 	$(CC) $(CFLAGS) -o getopt_test getopt_test.c
 
+getopt_long_test: getopt_long_test.c
+	$(CC) $(CFLAGS) -o getopt_long_test getopt_long_test.c
+
 ya_getopt_test: getopt_test.c ../ya_getopt.c ../ya_getopt.h
 	$(CC) $(CFLAGS) -o ya_getopt_test -DUSE_YA_GETOPT -I.. getopt_test.c  ../ya_getopt.c
 
+ya_getopt_long_test: getopt_long_test.c ../ya_getopt.c ../ya_getopt.h
+	$(CC) $(CFLAGS) -o ya_getopt_long_test -DUSE_YA_GETOPT -I.. getopt_long_test.c  ../ya_getopt.c
+
 clean:
-	$(RM) getopt_test ya_getopt_test getopt_test.out ya_getopt_test.out
+	$(RM) $(PROGS) getopt_test.out getopt_long_test.out ya_getopt_test.out ya_getopt_long_test.out
